{{- if .Values.httpRoute2 -}}
{{- if .Values.httpRoute2.enabled -}}
{{- $fullName := include "app.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-2
  {{- with .Values.httpRoute2.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- range .Values.httpRoute2.parentRefs }}
        - name: {{ .name | quote }}
    {{- end }}
  hostnames:
    {{- range .Values.httpRoute2.hosts }}
    - {{ . | quote }}
    {{- end }}

## define paths    
  rules:
    - matches:
        {{- range .Values.httpRoute2.paths }}
        - path:
            type: {{ .type | quote }}
            value: {{ .value | quote }}
        {{- end }}

## define backend refs
      {{- if .Values.httpRoute2.backends }}
      backendRefs:
        {{- range .Values.httpRoute2.backends }}
        - name: {{ .name }}
          port: {{ .port }}
          weight: {{ .weight }}
        {{- end }}
      {{- end }}
{{- end }}
{{- end }}