{{- if and (hasKey .Values "istio") .Values.istio .Values.istio.enabled }}
{{- if .Values.istio.VirtualService -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "app.fullname" . }}
spec:
  {{- with .Values.istio.VirtualService.hosts }}
  hosts: 
  - {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.istio.VirtualService.gateways }}
  gateways: 
  - {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.istio.VirtualService.http }}
  http: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
