{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.port  }}
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
      name: {{ .Values.service.name | default "http" }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    {{- end }} 
    {{- if .Values.service.ports  }}
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default "http" }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name | default "http" }}
      {{- if eq .type "NodePort" }}
      nodePort: {{ .nodePort }}
      {{- end }} 
    {{- end }} 
    {{- end }} 
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.internalTrafficPolicy }}
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy }}
  {{- end }}
{{- end }}
